// import 'package:flutter_riverpod/flutter_riverpod.dart';
// import '../../../../core/models/favorite.dart';
// import '../../../../domain/usecases/favorites/favorite_use_case_provider.dart';
// import '../../../../domain/usecases/favorites/favorite_use_cases.dart';
//
// final favoriteProvider =
// StateNotifierProvider<FavoritesNotifier, FavoritesState>((ref) {
//   return FavoritesNotifier(
//     getFavoritesUseCase: ref.watch(getFavoritesUseCaseProvider),
//     addFavoriteUseCase: ref.watch(addFavoriteUseCaseProvider),
//     removeFavoriteUseCase: ref.watch(removeFavoriteUseCaseProvider),
//   )..loadFavorites();
// });
//
// class FavoritesNotifier extends StateNotifier<FavoritesState> {
//   final GetFavoritesUseCase getFavoritesUseCase;
//   final AddFavoriteUseCase addFavoriteUseCase;
//   final RemoveFavoriteUseCase removeFavoriteUseCase;
//
//   // Store current user ID (you might want to get this from auth provider)
//   final String _currentUserId = "3"; // TODO: Replace with actual user ID
//
//   FavoritesNotifier({
//     required this.getFavoritesUseCase,
//     required this.addFavoriteUseCase,
//     required this.removeFavoriteUseCase,
//   }) : super(const FavoritesState());
//
//   /// LOAD
//   Future<void> loadFavorites() async {
//     state = state.copyWith(isLoading: true);
//     try {
//       final favorites = await getFavoritesUseCase.execute(_currentUserId);
//       state = state.copyWith(
//         favorites: favorites,
//         isLoading: false,
//         error: null,
//       );
//     } catch (e) {
//       state = state.copyWith(isLoading: false, error: e.toString());
//     }
//   }
//
//   /// CHECK if product is favorite
//   bool isFavorite(String productId) {
//     return state.favorites.any((fav) => fav.productId == productId);
//   }
//
//   /// ADD favorite (with product details)
//   Future<void> addFavorite({
//     required String productId,
//     required String productName,
//     required String productImageUrl,
//     required double productPrice,
//   }) async {
//     try {
//       // Create Favorite object
//       final favorite = Favorite(
//         id: '', // Will be generated by server
//         userId: _currentUserId,
//         productId: productId,
//         productName: productName,
//         productImageUrl: productImageUrl,
//         productPrice: productPrice,
//       );
//
//       await addFavoriteUseCase.execute(favorite);
//
//       // Optimistically update UI
//       state = state.copyWith(
//         favorites: [...state.favorites, favorite],
//       );
//
//       // Refresh from server to get actual ID
//       await loadFavorites();
//     } catch (e) {
//       state = state.copyWith(error: e.toString());
//       rethrow;
//     }
//   }
//
//   /// REMOVE favorite
//   Future<void> removeFavorite(String productId) async {
//     try {
//       // Optimistically remove from UI
//       final updatedFavorites = state.favorites
//           .where((fav) => fav.productId != productId)
//           .toList();
//       state = state.copyWith(favorites: updatedFavorites);
//
//       // Call API to remove
//       await removeFavoriteUseCase.execute(_currentUserId, productId);
//
//       // Optional: reload to ensure sync
//       // await loadFavorites();
//     } catch (e) {
//       // If error, reload to restore correct state
//       await loadFavorites();
//       state = state.copyWith(error: e.toString());
//       rethrow;
//     }
//   }
//
//   /// TOGGLE favorite
//   Future<void> toggleFavorite({
//     required String productId,
//     String? productName,
//     String? productImageUrl,
//     double? productPrice,
//   }) async {
//     if (isFavorite(productId)) {
//       await removeFavorite(productId);
//     } else {
//       if (productName != null && productImageUrl != null && productPrice != null) {
//         await addFavorite(
//           productId: productId,
//           productName: productName,
//           productImageUrl: productImageUrl,
//           productPrice: productPrice,
//         );
//       } else {
//         throw Exception('Product details required to add to favorites');
//       }
//     }
//   }
//
//   /// CLEAR all favorites
//   Future<void> clearAllFavorites() async {
//     try {
//       final originalFavorites = List<Favorite>.from(state.favorites);
//       state = state.copyWith(favorites: []);
//
//       // Remove all from server
//       for (final favorite in originalFavorites) {
//         await removeFavoriteUseCase.execute(_currentUserId, favorite.productId);
//       }
//     } catch (e) {
//       // Restore original state on error
//       // state = state.copyWith(favorites: originalFavorites);
//       // state = state.copyWith(error: e.toString());
//       rethrow;
//     }
//   }
// }
//
// class FavoritesState {
//   final List<Favorite> favorites;
//   final bool isLoading;
//   final String? error;
//
//   const FavoritesState({
//     this.favorites = const [],
//     this.isLoading = false,
//     this.error,
//   });
//
//   FavoritesState copyWith({
//     List<Favorite>? favorites,
//     bool? isLoading,
//     String? error,
//   }) {
//     return FavoritesState(
//       favorites: favorites ?? this.favorites,
//       isLoading: isLoading ?? this.isLoading,
//       error: error,
//     );
//   }
// }